#!/bin/bash

if [ "$(stat -c "%Y" "${FECRU_INST}/bin/fisheyectl.sh")" -eq "0" ]; then
  sed --in-place "s~#!/bin/sh~#!/bin/sh \n FISHEYE_INST=${FECRU_HOME}~" ${FECRU_INST}/bin/fisheyectl.sh
fi

if [ "$(stat -c "%Y" "${FECRU_INST}/config.xml")" -eq "0" ]; then
  if [ -n "${TOMCAT_CONTEXT_PATH}" ]; then
    xmlstarlet ed --inplace --insert '/config/web-server' --type "attr" --name "context" --value "${TOMCAT_CONTEXT_PATH}" "${FECRU_INST}/config.xml"
  fi
fi

if [ ! -f "${FECRU_HOME}/config.xml" ]; then
  cp ${FECRU_INST}/config.xml ${FECRU_HOME}/config.xml
fi

exec "$@"
